"""WAF (Web Application Firewall) detection and fingerprinting module.

Identifies WAFs protecting web applications using:
- Passive detection: analyzing response headers and cookies
- Active detection: sending malicious payloads to trigger WAF blocks
- Fingerprinting: matching responses against known WAF signatures

Supports 20+ WAF vendors including Cloudflare, AWS WAF, ModSecurity,
Akamai, Imperva, F5 BIG-IP, and more.
"""

from __future__ import annotations

import asyncio
import re
from dataclasses import dataclass, field
from typing import Optional

import httpx


# ── Data structures ──────────────────────────────────────────────────────────


@dataclass
class WafSignature:
    """Signature for identifying a specific WAF."""
    name: str
    vendor: str = ""
    description: str = ""
    # Passive: response header patterns
    header_patterns: dict[str, list[str]] = field(default_factory=dict)
    # Passive: cookie patterns
    cookie_patterns: list[str] = field(default_factory=list)
    # Passive: response body patterns
    body_patterns: list[str] = field(default_factory=list)
    # Active: status code when malicious request is blocked
    block_status_codes: list[int] = field(default_factory=lambda: [403, 406, 429, 503])
    # Active: body patterns in blocked response
    block_body_patterns: list[str] = field(default_factory=list)


@dataclass
class WafResult:
    """Result of WAF detection for a single URL."""
    url: str
    detected_wafs: list[dict] = field(default_factory=list)
    passive_matches: list[str] = field(default_factory=list)
    active_confirmed: list[str] = field(default_factory=list)
    is_protected: bool = False
    error: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "url": self.url,
            "is_protected": self.is_protected,
            "detected_wafs": self.detected_wafs,
            "passive_matches": self.passive_matches,
            "active_confirmed": self.active_confirmed,
        }


@dataclass
class WafReport:
    """Aggregated WAF detection report."""
    results: dict[str, WafResult] = field(default_factory=dict)
    total_urls_checked: int = 0
    total_protected: int = 0

    def to_dict(self) -> dict:
        return {
            "total_urls_checked": self.total_urls_checked,
            "total_protected": self.total_protected,
            "results": {
                url: r.to_dict() for url, r in self.results.items()
            },
        }


# ── WAF Signature Database ───────────────────────────────────────────────────

WAF_SIGNATURES: list[WafSignature] = [
    # === Cloud WAFs ===
    WafSignature(
        name="Cloudflare",
        vendor="Cloudflare, Inc.",
        description="Cloudflare WAF/CDN — most widely used",
        header_patterns={
            "server": ["cloudflare"],
            "cf-ray": [".+"],
            "cf-cache-status": [".+"],
        },
        cookie_patterns=["__cfduid", "__cf_bm", "cf_clearance"],
        body_patterns=["cloudflare-nginx", "Attention Required! | Cloudflare"],
        block_status_codes=[403, 503],
        block_body_patterns=[
            "cf-error-page", "cloudflare", "Attention Required",
            "Please complete the security check",
        ],
    ),
    WafSignature(
        name="AWS WAF",
        vendor="Amazon Web Services",
        description="AWS WAF / Shield — cloud-native WAF",
        header_patterns={
            "x-amzn-requestid": [".+"],
            "x-amzn-errortype": [".+"],
        },
        block_status_codes=[403, 400],
        block_body_patterns=[
            "x-amzn-RequestId", "x-amzn-ErrorType",
            "Request blocked", "WAF",
        ],
    ),
    WafSignature(
        name="AWS CloudFront",
        vendor="Amazon Web Services",
        description="AWS CloudFront with WAF",
        header_patterns={
            "x-cache": ["Error from cloudfront", "CloudFront"],
            "x-amz-cf-id": [".+"],
            "server": ["CloudFront"],
        },
        block_status_codes=[403, 404],
        block_body_patterns=[
            "cloudfront", "Generated by CloudFront",
            "Bad request", "The request could not be satisfied",
        ],
    ),
    WafSignature(
        name="Azure Front Door",
        vendor="Microsoft",
        description="Azure Front Door / WAF",
        header_patterns={
            "x-azure-ref": [".+"],
            "x-cdn": ["Azure"],
            "x-sdl": ["azure"],
        },
        block_status_codes=[403, 503],
        block_body_patterns=["Azure WAF", "azureedge.net", "WAF blocked"],
    ),
    WafSignature(
        name="Google Cloud Armor",
        vendor="Google",
        description="Google Cloud Armor WAF",
        header_patterns={
            "x-goog-": [".+"],
            "x-cloud-trace-context": [".+"],
        },
        block_status_codes=[403, 502],
        block_body_patterns=["Google Cloud Armor", "cloud.google.com"],
    ),
    WafSignature(
        name="Akamai",
        vendor="Akamai Technologies",
        description="Akamai Kona Site Defender / WAF",
        header_patterns={
            "server": ["AkamaiGHost", "AkamaiNetStorage"],
            "x-akamai-": [".+"],
            "x-ats": [".+"],
        },
        cookie_patterns=["ak_bmsc", "bm_sz", "akacd_"],
        block_status_codes=[403, 406],
        block_body_patterns=["Akamai", "Reference #", "Access Denied"],
    ),
    WafSignature(
        name="Imperva (Incapsula)",
        vendor="Imperva",
        description="Imperva Incapsula WAF",
        header_patterns={
            "x-cdn": ["Incapsula", "Imperva"],
            "x-iinfo": [".+"],
        },
        cookie_patterns=["incap_ses_", "visid_incap_", "nlbi_"],
        block_status_codes=[403, 406, 509],
        block_body_patterns=[
            "Incapsula", "Imperva", "_Incapsula_Resource",
            "Blocked because of an application firewall",
        ],
    ),
    WafSignature(
        name="Sucuri",
        vendor="Sucuri (GoDaddy)",
        description="Sucuri CloudProxy WAF",
        header_patterns={
            "x-sucuri-id": [".+"],
            "x-sucuri-cache": [".+"],
        },
        cookie_patterns=["sucuri_cloudproxy"],
        block_status_codes=[403, 503],
        block_body_patterns=["Sucuri", "CloudProxy"],
    ),
    WafSignature(
        name="StackPath (MaxCDN)",
        vendor="StackPath",
        description="StackPath WAF / CDN",
        header_patterns={
            "x-powered-by": ["StackPath"],
            "server": ["StackPath"],
        },
        block_status_codes=[403],
    ),
    WafSignature(
        name="Fastly",
        vendor="Fastly",
        description="Fastly CDN (may include WAF)",
        header_patterns={
            "x-fastly-": [".+"],
            "x-cache": ["HIT", "MISS", "STALE"],
        },
        cookie_patterns=["fastly-"],
        block_status_codes=[503],
        block_body_patterns=["Fastly error"],
    ),
    WafSignature(
        name="Cloudbric",
        vendor="Cloudbric",
        description="Cloudbric WAF",
        header_patterns={
            "x-bric": [".+"],
            "server": ["Cloudbric"],
        },
        block_status_codes=[403],
        block_body_patterns=["Cloudbric", "Malicious Request"],
    ),

    # === On-Premise / Open Source WAFs ===
    WafSignature(
        name="ModSecurity",
        vendor="Trustwave / OWASP",
        description="ModSecurity (open-source WAF)",
        header_patterns={
            "server": ["ModSecurity"],
        },
        block_status_codes=[403, 400, 406],
        block_body_patterns=[
            "ModSecurity", "Not Acceptable", "Request blocked by ModSecurity",
            "This error was generated by Mod_Security",
        ],
    ),
    WafSignature(
        name="NAXSI",
        vendor="NBS System",
        description="NAXSI (Nginx Anti XSS & SQL Injection)",
        header_patterns={
            "x-naxsi": [".+"],
        },
        cookie_patterns=["naxsi"],
        block_status_codes=[403],
        block_body_patterns=["naxsi", "blocked by naxsi"],
    ),
    WafSignature(
        name="F5 BIG-IP ASM",
        vendor="F5 Networks",
        description="F5 BIG-IP Application Security Manager",
        header_patterns={
            "x-f5-asm": [".+"],
            "server": ["BigIP"],
        },
        cookie_patterns=["TS[0-9a-f]+"],
        block_status_codes=[403, 404, 500],
        block_body_patterns=[
            "The page you requested was blocked", "F5 Networks", "ASM",
            "ts_", "Technical Support",
        ],
    ),
    WafSignature(
        name="F5 BIG-IP APM",
        vendor="F5 Networks",
        description="F5 BIG-IP Access Policy Manager",
        header_patterns={
            "server": ["BigIP"],
        },
        cookie_patterns=["MRHSession", "F5_ST"],
        block_status_codes=[403, 404],
    ),
    WafSignature(
        name="Barracuda WAF",
        vendor="Barracuda Networks",
        description="Barracuda Web Application Firewall",
        header_patterns={
            "x-barracuda": [".+"],
            "server": ["Barracuda"],
        },
        cookie_patterns=["barra_counter_session"],
        block_status_codes=[403, 410],
        block_body_patterns=["Barracuda", "barracuda.net"],
    ),
    WafSignature(
        name="Fortinet FortiWeb",
        vendor="Fortinet",
        description="Fortinet FortiWeb WAF",
        header_patterns={
            "server": ["FortiWeb"],
        },
        cookie_patterns=["FORTIWAFSID"],
        block_status_codes=[403, 406],
        block_body_patterns=["FortiWeb", "fortinet.com"],
    ),
    WafSignature(
        name="Citrix NetScaler (ADC)",
        vendor="Citrix",
        description="Citrix NetScaler Application Delivery Controller",
        header_patterns={
            "server": ["NetScaler", "NS"],
        },
        cookie_patterns=["NSC_", "citrix_ns_id"],
        block_status_codes=[403, 400],
    ),
    WafSignature(
        name="Radware AppWall",
        vendor="Radware",
        description="Radware AppWall WAF",
        header_patterns={
            "x-sig": [".+"],
            "server": ["Radware"],
        },
        cookie_patterns=["radware"],
        block_status_codes=[403],
        block_body_patterns=["Radware", "AppWall"],
    ),
    WafSignature(
        name="Palo Alto",
        vendor="Palo Alto Networks",
        description="Palo Alto Networks Next-Gen Firewall",
        header_patterns={
            "server": ["PAN-"],
        },
        cookie_patterns=["pan_"],
        block_status_codes=[403],
        block_body_patterns=["Palo Alto", "PAN-"],
    ),
    WafSignature(
        name="WordPress WAF",
        vendor="WordPress / Jetpack",
        description="WordPress-level WAF (Jetpack, Wordfence, etc.)",
        block_status_codes=[403, 503],
        block_body_patterns=[
            "Wordfence", "blocked by Wordfence", "Jetpack",
            "Request blocked by", "waf",
        ],
    ),
    WafSignature(
        name="Reblaze",
        vendor="Reblaze Technologies",
        description="Reblaze WAF / CDN",
        header_patterns={
            "x-reblaze-": [".+"],
        },
        block_status_codes=[403, 429],
    ),
    WafSignature(
        name="Comodo WAF / cWatch",
        vendor="Comodo",
        description="Comodo cWatch WAF",
        header_patterns={
            "server": ["Comodo"],
        },
        cookie_patterns=["comodo_"],
        block_status_codes=[403],
        block_body_patterns=["Protected by cWatch", "Comodo Security"],
    ),
    WafSignature(
        name="WebKnight",
        vendor="AQTRONIX",
        description="WebKnight WAF (IIS)",
        header_patterns={
            "server": ["WebKnight"],
        },
        block_status_codes=[403, 404, 500],
        block_body_patterns=["WebKnight", "AQTRONIX"],
    ),
    WafSignature(
        name="Safe3WAF",
        vendor="Safe3",
        description="Safe3WAF",
        header_patterns={
            "server": ["Safe3WAF", "Safe3 Web Firewall"],
        },
        block_status_codes=[403],
        block_body_patterns=["Safe3WAF", "Safe3"],
    ),
    WafSignature(
        name="URLScan",
        vendor="Microsoft",
        description="Microsoft IIS URLScan / Request Filtering",
        block_status_codes=[404, 405, 414],
        block_body_patterns=["URLScan", "Rejected-By-UrlScan"],
    ),
    WafSignature(
        name="EdgeCast (Verizon CDN)",
        vendor="Edgio (formerly Verizon)",
        description="Edgio/Verizon CDN WAF",
        header_patterns={
            "server": ["ECS", "EdgeCast"],
        },
        block_status_codes=[403],
    ),
    WafSignature(
        name="ChinaCache",
        vendor="ChinaCache",
        description="ChinaCache CDN WAF",
        header_patterns={
            "powered-by-chinacache": [".+"],
            "server": ["ChinaCache"],
        },
    ),
    WafSignature(
        name="URLRewriter (ISAPI)",
        vendor="HeliconTech",
        description="Helicon ISAPI Rewrite / URLRewriter",
        header_patterns={
            "x-powered-by": ["ISAPI_Rewrite|Helicon"],
            "x-rewrite": [".+"],
        },
    ),
    WafSignature(
        name="Profense",
        vendor="ArmorLogic",
        description="Profense WAF",
        header_patterns={
            "server": ["Profense"],
        },
        cookie_patterns=["PLBS"],
        block_status_codes=[403],
    ),
    WafSignature(
        name="BroadWeb",
        vendor="BroadWeb",
        description="BroadWeb WAF",
        header_patterns={
            "server": ["BroadWeb"],
        },
        block_status_codes=[403, 400],
    ),
    WafSignature(
        name="Airlock",
        vendor="Ergon",
        description="Ergon Airlock WAF",
        header_patterns={
            "x-airlock": [".+"],
            "server": ["Airlock"],
        },
        block_status_codes=[403, 406],
        block_body_patterns=["Airlock"],
    ),
    WafSignature(
        name="Varnish",
        vendor="Varnish Software",
        description="Varnish Cache (may be in front of WAF)",
        header_patterns={
            "x-varnish": [".+"],
            "via": ["varnish"],
        },
    ),
    WafSignature(
        name="DenyAll",
        vendor="DenyAll",
        description="DenyAll rWeb WAF",
        header_patterns={
            "server": ["DenyAll"],
        },
        cookie_patterns=["session_reuid"],
        block_status_codes=[403],
        block_body_patterns=["DenyAll", "rWeb"],
    ),
    WafSignature(
        name="SiteGround",
        vendor="SiteGround",
        description="SiteGround Security/WAF",
        header_patterns={
            "x-sg-": [".+"],
        },
        block_status_codes=[403, 503],
        block_body_patterns=["SiteGround", "blocked by SG"],
    ),
    WafSignature(
        name="Terra-WAF",
        vendor="Terra",
        description="Terra WAF",
        header_patterns={
            "server": ["Terra-WAF", "Terra WAF"],
        },
        block_status_codes=[403, 406],
    ),
    WafSignature(
        name="KS-WAF",
        vendor="KnownSec",
        description="KnownSec WAF (Chinese security vendor)",
        header_patterns={
            "x-powered-by": ["KS-WAF", "KnownSec"],
        },
        block_status_codes=[403],
        block_body_patterns=["KnownSec", "KS-WAF"],
    ),
    WafSignature(
        name="Yundun",
        vendor="Alibaba Cloud",
        description="Alibaba Cloud Yundun WAF",
        header_patterns={
            "x-yundun": [".+"],
            "server": ["Yundun", "Aliyun"],
        },
        block_status_codes=[403],
        block_body_patterns=["Yundun", "aliyunwaf"],
    ),
    WafSignature(
        name="Aliyun (Alibaba Cloud)",
        vendor="Alibaba Cloud",
        description="Alibaba Cloud WAF",
        header_patterns={
            "server": ["Aliyun", "taobao"],
        },
        cookie_patterns=["aliyungf_tc"],
        block_status_codes=[403],
        block_body_patterns=["Aliyun", "SLB"],
    ),
    WafSignature(
        name="Tencent Cloud WAF",
        vendor="Tencent",
        description="Tencent Cloud Web Application Firewall",
        header_patterns={
            "server": ["Tencent"],
        },
        cookie_patterns=["tencent_"],
        block_status_codes=[403],
    ),
    WafSignature(
        name="Huawei Cloud WAF",
        vendor="Huawei",
        description="Huawei Cloud WAF",
        header_patterns={
            "server": ["HuaweiCloudWAF", "Huawei"],
        },
        block_status_codes=[403],
    ),
    WafSignature(
        name="Greywizard",
        vendor="Grey Wizard",
        description="Greywizard WAF",
        header_patterns={
            "x-greywizard": [".+"],
            "server": ["Greywizard"],
        },
        block_status_codes=[403],
    ),
]


# Passive test payloads to trigger WAF (SQL injection patterns)
ACTIVE_PAYLOADS = [
    "' OR '1'='1",
    "' UNION SELECT * FROM users--",
    "<script>alert(1)</script>",
    "../../../etc/passwd",
    "1 UNION SELECT password FROM admin--",
    "'; DROP TABLE users--",
    "1 AND 1=1 UNION SELECT 1,2,3--",
]


# ── Passive Detection ──────────────────────────────────────────────────────


async def detect_passive(
    url: str,
    timeout: float = 10.0,
    proxy_url: Optional[str] = None,
) -> WafResult:
    """Passively detect WAF by analyzing response headers and cookies.

    Makes a normal request and checks for WAF-specific headers and cookies.
    """
    result = WafResult(url=url)

    client_kwargs: dict = {
        "verify": False,
        "timeout": httpx.Timeout(timeout),
        "follow_redirects": True,
    }
    if proxy_url:
        client_kwargs["proxies"] = proxy_url

    try:
        async with httpx.AsyncClient(**client_kwargs) as client:
            resp = await client.get(url, headers={
                "User-Agent": (
                    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
                    "(KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"
                ),
            })

            headers_lower = {k.lower(): v for k, v in resp.headers.items()}
            body_lower = resp.text.lower()
            cookies = dict(resp.cookies)

            for sig in WAF_SIGNATURES:
                matched_passive = False
                matched_reasons: list[str] = []

                # Check header patterns
                for header_key, patterns in sig.header_patterns.items():
                    if header_key in headers_lower:
                        header_val = headers_lower[header_key]
                        for pattern in patterns:
                            if re.search(pattern, header_val, re.I):
                                matched_passive = True
                                matched_reasons.append(f"header:{header_key}={header_val[:50]}")
                                break

                # Check cookie patterns
                for cookie_pattern in sig.cookie_patterns:
                    for cookie_name in cookies:
                        if re.search(cookie_pattern, cookie_name, re.I):
                            matched_passive = True
                            matched_reasons.append(f"cookie:{cookie_name}")
                            break

                # Check body patterns (passive)
                for body_pattern in sig.body_patterns:
                    if body_pattern.lower() in body_lower:
                        matched_passive = True
                        matched_reasons.append(f"body matched: {body_pattern[:40]}")
                        break

                if matched_passive:
                    result.is_protected = True
                    result.passive_matches.extend(matched_reasons)
                    result.detected_wafs.append({
                        "name": sig.name,
                        "vendor": sig.vendor,
                        "description": sig.description,
                        "match_type": "passive",
                        "reason": ", ".join(matched_reasons),
                    })

    except (httpx.TimeoutException, httpx.ConnectError, httpx.HTTPError) as e:
        result.error = str(e)
    except Exception as e:
        result.error = str(e)

    return result


# ── Active Detection ────────────────────────────────────────────────────────


async def detect_active(
    url: str,
    matched_signatures: Optional[list[WafSignature]] = None,
    timeout: float = 10.0,
    proxy_url: Optional[str] = None,
) -> WafResult:
    """Actively probe for WAF by sending malicious payloads.

    Only checks signatures that were matched in passive detection
    (or all signatures if none were passively matched).

    Args:
        url: Target URL.
        matched_signatures: Signatures already matched passively (to narrow active checks).
        timeout: Request timeout.
        proxy_url: Optional proxy URL.

    Returns:
        WafResult with active confirmation data.
    """
    result = WafResult(url=url)
    signatures = matched_signatures or WAF_SIGNATURES

    if not signatures:
        return result

    client_kwargs: dict = {
        "verify": False,
        "timeout": httpx.Timeout(timeout),
        "follow_redirects": False,
    }
    if proxy_url:
        client_kwargs["proxies"] = proxy_url

    async with httpx.AsyncClient(**client_kwargs) as client:
        for payload in ACTIVE_PAYLOADS:
            try:
                # Send request with the malicious payload as a query param
                response = await client.get(
                    url,
                    params={"q": payload, "id": payload, "search": payload},
                    headers={
                        "User-Agent": f"'{payload}",
                        "Accept": "text/html,*/*",
                    },
                )

                status = response.status_code
                body = response.text.lower()

                for sig in signatures:
                    # Check if blocked status matches
                    if status in sig.block_status_codes:
                        # Check block body patterns
                        for block_pattern in sig.block_body_patterns:
                            if block_pattern.lower() in body:
                                if sig.name not in result.active_confirmed:
                                    result.active_confirmed.append(sig.name)
                                    result.is_protected = True
                                    result.detected_wafs.append({
                                        "name": sig.name,
                                        "vendor": sig.vendor,
                                        "description": sig.description,
                                        "match_type": "active",
                                        "reason": f"blocked with status {status}, matched '{block_pattern}'",
                                    })
                                break
            except (httpx.TimeoutException, httpx.HTTPError):
                continue
            except Exception:
                continue

    return result


# ── Main Orchestrator ───────────────────────────────────────────────────────


async def detect_waf(
    urls: list[str],
    enable_active: bool = True,
    proxy_url: Optional[str] = None,
    max_concurrent: int = 5,
) -> WafReport:
    """Detect WAFs protecting a list of URLs.

    Two-phase detection:
    1. Passive: analyze response headers/cookies/body for WAF signatures
    2. Active: send malicious payloads to confirm WAF behavior

    Args:
        urls: List of URLs to check.
        enable_active: Whether to perform active probing (default: True).
        proxy_url: Optional proxy URL.
        max_concurrent: Maximum concurrent requests.

    Returns:
        WafReport with detection results.
    """
    report = WafReport()
    semaphore = asyncio.Semaphore(max_concurrent)

    async def detect_one(url: str) -> WafResult:
        async with semaphore:
            # Phase 1: Passive detection
            passive_result = await detect_passive(url, proxy_url=proxy_url)
            report.total_urls_checked += 1
            if passive_result.is_protected:
                report.total_protected += 1

            # Phase 2: Active detection (optional)
            if enable_active and passive_result.is_protected:
                # Get signatures that matched passively for targeted active checks
                matched_names = {w["name"] for w in passive_result.detected_wafs}
                matched_sigs = [s for s in WAF_SIGNATURES if s.name in matched_names]
                active_result = await detect_active(
                    url, matched_signatures=matched_sigs, proxy_url=proxy_url,
                )
                # Merge active results
                passive_result.active_confirmed = active_result.active_confirmed
                for waf in active_result.detected_wafs:
                    if waf["name"] not in {w["name"] for w in passive_result.detected_wafs}:
                        passive_result.detected_wafs.append(waf)
                    passive_result.is_protected = True

            elif enable_active and not passive_result.is_protected:
                # No passive match — try broad active detection
                active_result = await detect_active(url, proxy_url=proxy_url)
                if active_result.is_protected:
                    passive_result.is_protected = True
                    passive_result.detected_wafs = active_result.detected_wafs
                    passive_result.active_confirmed = active_result.active_confirmed

            return passive_result

    tasks = [detect_one(url) for url in urls]
    results = await asyncio.gather(*tasks, return_exceptions=True)

    for i, url in enumerate(urls):
        result_val = results[i]
        if isinstance(result_val, WafResult):
            report.results[url] = result_val
        else:
            report.results[url] = WafResult(url=url, error=str(result_val) if isinstance(result_val, Exception) else None)

    return report
